Tasques/Models/GROUPS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasques.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPS
    {
        public int IDGROUP { get; set; }
        public string GROUPNAME { get; set; }
    }
}

Tasques/Controllers/GROUPSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tasques.Models;

namespace Tasques.Controllers
{
    public class GROUPSController : Controller
    {
        private tasquesEntities db = new tasquesEntities();

        // GET: GROUPS
        public ActionResult Index()
        {
            return View(db.GROUPS.ToList());
        }

        // GET: GROUPS/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GROUPS gROUPS = db.GROUPS.Find(id);
            if (gROUPS == null)
            {
                return HttpNotFound();
            }
            return View(gROUPS);
        }

        // GET: GROUPS/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GROUPS/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDGROUP,GROUPNAME")] GROUPS gROUPS)
        {
            if (ModelState.IsValid)
            {
                db.GROUPS.Add(gROUPS);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gROUPS);
        }

        // GET: GROUPS/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GROUPS gROUPS = db.GROUPS.Find(id);
            if (gROUPS == null)
            {
                return HttpNotFound();
            }
            return View(gROUPS);
        }

        // POST: GROUPS/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDGROUP,GROUPNAME")] GROUPS gROUPS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gROUPS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gROUPS);
        }

        // GET: GROUPS/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GROUPS gROUPS = db.GROUPS.Find(id);
            if (gROUPS == null)
            {
                return HttpNotFound();
            }
            return View(gROUPS);
        }

        // POST: GROUPS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GROUPS gROUPS = db.GROUPS.Find(id);
            db.GROUPS.Remove(gROUPS);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tasques/Views/GROUPS/Create.cshtml
@model Tasques.Models.GROUPS

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>GROUPS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GROUPNAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GROUPNAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GROUPNAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href='@Url.Action("Index")'>
        <img src='@Url.Content("~/fonts/tornar.png")' height="50" width="50" />
    </a>Tornar
</div>

Tasques/Views/GROUPS/Delete.cshtml
@model Tasques.Models.GROUPS

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GROUPS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GROUPNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GROUPNAME)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tasques/Views/GROUPS/Details.cshtml
@model Tasques.Models.GROUPS

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>GROUPS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GROUPNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GROUPNAME)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDGROUP }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Tasques/Views/GROUPS/Edit.cshtml
@model Tasques.Models.GROUPS

@{
    ViewBag.Title = "EDICIÓ DE GRUPS";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EDICIÓ DE GRUPS</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>GROUPS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDGROUP)

        <div class="form-group">
            @Html.LabelFor(model => model.GROUPNAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GROUPNAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GROUPNAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success btn-large" />
            </div>
        </div>
    </div>
}

<div>
    <a href='@Url.Action("Index")'>
        <img src='@Url.Content("~/fonts/tornar.png")' height="50" width="50" />
    </a>Tornar
</div>

Tasques/Views/GROUPS/Index.cshtml
@model IEnumerable<Tasques.Models.GROUPS>

@{
    ViewBag.Title = "ADMINISTRACIÓ DE GRUPS";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ADMINISTRACIÓ DE GRUPS</h2>

<p>
    @Html.ActionLink("Nou grup", "Create", "GROUPS", null, new { @class = "btn btn-primary btn-large" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GROUPNAME)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.GROUPNAME)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.IDGROUP }, new { @class = "btn btn-primary btn-large" }) 
            @*@Html.ActionLink("Details", "Details", new { id=item.IDGROUP }) |*@
            @Html.ActionLink("Borrar", "Delete", new { id=item.IDGROUP }, new { @class = "btn btn-danger btn-large" })
        </td>
    </tr>
}

</table>